name: Lab 4 CI

on:
  push:
    branches:
      - lab4
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - lab4
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  trigger-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show trigger context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"

    
