name: Pipeline for Lab 2

on:
    push:
        branches:
        - lab3

jobs:
    run-lab2:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: pnpm

        - name: Enable pnpm
          run: corepack enable
        
        - name: Run Lab 2 Script
          run: |
            echo "Starting Lab 2 Pipeline..."
            chmod +x ./deliverables/lab02/lab2.sh
            ./deliverables/lab02/lab2.sh
            echo "Lab 2 Pipeline Completed."
